algoritmo "NomeSalario"
// Função : Ler o nome e o salário de um funcionario
// Autor : Rafael Calazans
// Data : 13/11/2024
// Seção de Declarações 
var
NOME: caractere
SALARIO: real
inicio
// Seção de Comandos
Escreva("Qual é o seu nome? ")
Leia(NOME)
Escreva("Qual é o seu salário? ")
Leia(SALARIO)
EscrevaL("O funcionario ", NOME, " tem um salário de R$", SALARIO:4:2, " em Junho" )
fimalgoritmo
