algoritmo "exercicio-04"
// Função : Somar dois valores e mostrar para o usuário
// Autor : Rafael Calazans
// Data : 13/11/2024
// Seção de Declarações 
var
VALOR01, VALOR02, SOMA: REAL
inicio
// Seção de Comandos
Escreva("Digite um valor: ")
Leia(Valor01)
Escreva("Digite outro valor: ")
Leia(Valor02)
SOMA <- VALOR01 + VALOR02
EscrevaL("A soma entre ", Valor01, " e", Valor02, " é igaul a", SOMA)
fimalgoritmo
