algoritmo "Contagem"
// Função : Pedir ao usuario u número inteiro e positivo e mostra a contagem
// Autor :
// Data : 24/10/2024
// Seção de Declarações 
var
Cont, N: Inteiro
inicio
// Seção de Comandos
Cont <- 1
Escreva("Me de um número inteiro e positivo! ")
Leia(N)
Enquanto (Cont <= N) faca
         Escreva(Cont)
         Cont <- Cont + 1
FimEnquanto
EscrevaL(" Acabou!")
fimalgoritmo
