algoritmo "Contagem Regressiva"
// Função : Fazer contagem regressiva de 30 até 1, marcando os divisiveis de 4
// Autor : Rafael Calazans
// Data : 24/10/2024
// Seção de Declarações 
var
cont: inteiro
inicio
// Seção de Comandos
Cont <- 30
Enquanto (COnt >= 1) faca
         Se (Cont % 4=0) entao
            Escreva("[", Cont, "]")
         Senao
            escreva(COnt)
         FimSe
         Cont <- Cont - 1
FimEnquanto
fimalgoritmo
